version: '3.7'

services:
  postgres:
    image: postgres:14-alpine
    hostname: postgres
    container_name: go_template_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: master
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - postgres

  main:
    container_name: main
    build: ./
    restart: always
    env_file:
      - .env
    ports:
      - '8080:8080'
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres:postgres
    networks:
      - postgres
networks:
  postgres:
     driver: bridge